packages:
  - .

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - 'lightningcss'
  - 'sharp'
  - 'unrs-resolver'

# если вдруг что-то всё ещё рубится на CI, можно добить:
# neverBuiltDependencies: []
